version: '3.8'
services:
  mysql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-container
    environment:
      SA_PASSWORD: Heslo123
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork: